### ISSUE TITLE
Crash/Lock/Freeze consisently when highlighting/interacting with container/body/item whilst auto-loot has found something

### ISSUE THREAD

**Issue by rahaney** [fireundubh/fallout4#39] opened 2016-11-17 19:23 UTC
Firstly, many thanks for this mod. I use auto-loots in skyrim and witcher 3 for their ease. I am having issues with this mod however. 

When the mod is installed with Nexus and is turned off via the in-game pipboy menu, i have no issues at all and can play for hours, so my game and my saves are fine.

The freeze occurs always when i have something highlighted/interacting with say a container or body or mine and the auto-scanning has just found another object to pick up for me. 

There is no difference if the container/body has loot in or has already been emptied either manually or through the auto-loot process.
There is no difference if the radius is at minimum or maximum, neither when both containers and bodies are off and the mod is simply picking up surface items. 
I've tried the previous version too aswell as the silent mod workaround that helped with a few others. I've read all the comments/issues on here and cant see anything else to attempt.

I see a workround which may be qucik and easy to implement, that is to have a manul keybind to trigger the script rather than on a timer.
I'm open to any other suggestions,
Thanks,
R

**Comment by frostryder** [comment] 2016-11-18 03:58
I'm having the exact same issue. I stopped using auto-loot, decided to try it again... Froze within 5 minutes. Any ideas?

**Comment by rahaney** [comment] 2016-11-18 09:27
If it is some form of conflict between the auto loot scripts and container quick loots as I suspect then modifying the script to run off a key bind instead of a timer would solve it. 

Hoping that some of the others or the author will know how to implement the above or suggest a fix.

**Comment by rahaney** [comment] 2016-11-18 19:27
So, implementing key press detection needs f4se....
I've developed a slightly better approach, by removing the silent mod, I can hear when the script is triggered, and at that point I don't interact with anything until the sound goes. It's not foolproof by any means :(

**Comment by frostryder** [comment] 2016-11-19 02:34
What about an item in the aid section we could hotkey, that would pulse the loot script? We could handle the special hotkeys with other mods, if needs be :)

**Comment by rahaney** [comment] 2016-11-23 22:32
There's a mod called FO4 hotkeys at http://www.nexusmods.com/fallout4/mods/11664/? in which you can apparently run a script from a key bind, if anyone has the know how that would be awesome. 
This mod works but I'm ctd'ing every 5 minutes as it autoloots when I'm interacting with someone/thing. I'm really close to uninstalling it which would be a shame...:(

**Comment by frostryder** [comment] 2016-11-23 22:34
If you tell me what the script command is,  I can translate it to a hotkey.
I use that mod already 😊

**Comment by frostryder** [comment] 2016-11-23 23:22
For instance, mapping a key like this:       B=player.cios 3cc96
Kicks off VANS when you hit B. (amusingly, even if you don't buy VANS).

Mapping a key like this:    B=player.cf "actor.ChangeHeadPart" <ID>
changes your hair to the # specified in <ID> spot, when you hit B. Not sure why you'd want to, but this runs that script on the player.

**Comment by rahaney** [comment] 2016-11-24 08:55
That's the problem, looking at the code on the site it would need some rewriting since it uses timer calls.

**Comment by frostryder** [comment] 2016-11-24 20:39
Doesn't it simply call another function once the timer 'finishes'? Couldn't that function then just be tied to the activate of an item in inventory, ala Survival Quick Save by Gopher (http://www.nexusmods.com/fallout4/mods/12593/?)  It's a real hard lockup when it freezes, as well, the only way out is to hit Ctrl-Alt-Delete and sign out of my profile. The first thing I do every time when I come back is check here lol... Let me know if you'd like a guinea pig to test this, I've got years of experience as a game dev, c# programmer, etc... Would be happy to help however I can! :)

**Comment by frostryder** [comment] 2016-11-24 22:53
BTW -  The interesting thing about this hanging problem is that it does not happen in the auto-lockpick mod, when it empties a container. I'm assuming you're using similar code, I would. Maybe there's some small difference, or a delay needs to be added for the auto-loot mod? Like not just a delay between 'pulses', but maybe like 50 milliseconds between each item? Maybe you're just overloading the game? :)

**Comment by rahaney** [comment] 2016-11-25 09:39
I've tried all the distances and all the proc rates, I've also looked at whether there's a variable like ishighlighted with no such luck which we could add in to the checking part. 

The code is available on the front page of this for those with programming skills. I know fo4 hotkeys can be used to call a specific script but that's as far as I got. I generally turn it off if I'm running a mission now...

**Comment by frostryder** [comment] 2016-11-25 15:24
I looked at the source, can't do much with it at work, but I did notice that when AutoLockpick empties a box, it uses obj.getallitems. AutoLoot uses GetItems, which, I'm thinking, might be going too fast for the engine to keep up with...  I know this seems weird, but what about creating a dummy container object, adding the items to it, then using GetAllItems on that new 'container'? Or at least treat bodies and containers as objects, and use GetAllItems on that? :) I'm not sure that will help, but it's an idea? :)

**Comment by rahaney** [comment] 2016-11-26 15:13
Any ideas are good ideas at this point :)

**Comment by rahaney** [comment] 2016-11-26 15:13
Damn mobiles

**Comment by frostryder** [comment] 2016-11-26 16:59
The more I think about it, the more I think that if you changed AutoLoot to use GetAllItems on the containers, instead of parsing thru them and using GetItems, it might help a bunch! I'll look more at it this weekend, and I want to see if I can figure out why it hangs when the player looks at an item the script looks at. :)

**Comment by fireundubh** [comment] 2016-12-01 05:56
> When AutoLockpick empties a box, it uses obj.getallitems. AutoLoot uses GetItems.

I'm not sure what you're referencing. There are no functions named GetItems and GetAllItems.

To give you some background:

Auto Loot uses two looting approaches: filtered, and unfiltered.

In the filtered approach, Auto Loot loops through the items in a container, loops through the items in a formlist, compares each item in the container against the items in that formlist, and when a match is found, Auto Loot removes that item from the container to the player or a settlement workbench.

In the unfiltered approach, Auto Loot simply removes all items from a container to the player or a settlement workbench, disregarding the types of items, including whether they are quest items or items that need to be activated by the player first. Auto Loot can be configured to do this in the menu. This is not ideal.

> What about creating a dummy container object, adding the items to it, then using GetAllItems on that new 'container'?

Moving items to a dummy container would add another layer of separation between taking an item and adding that item to the player's inventory.

* If you are assuming that removing items through Papyrus has problems, then you would be doubling your chances at reproducing freezing issues because you would be running the code that removes items to a container twice. First, you would be removing items from a container to a dummy container, and second, you would be removing items from a dummy container to the player.

* If you are assuming that there is some sort of instancing issue where looting is not happening fast enough to beat the time taken by the system to clear a container object or its inventory from memory, then freezing while looting would be more pronounced without Auto Loot.

Freezes, in my experience, are generally caused by null reference exceptions. This is where some piece of a code somewhere in the chain is clearing or not filling a variable that is expected to be not null. As all of my functions are wrapped in condition statements to verify that the variables needed are not null, and wrapping these statements like so had no impact on the incidence of reported freezes, so I can conclude only that wherever the problem may be, it is not in my scripts.

I know you want to look at my scripts as a probable source of frustration because you have power over the scripts, but many people, including me, run Auto Loot without freezing. Furthermore, none of the freezes reported to me have been reproduceable. Why? I have no idea. Please report freezes to Bethesda. They are the only developers who can solve freezes, as they have the necessary debugging tools and symbols, and access to the Fallout 4 source code, to determine what is happening.

**Closed by fireundubh** 2016-12-01 05:56 UTC

**Comment by rahaney** [comment] 2016-12-01 14:29
I'm not sure why you've marked this as closed... this freeze has been reported several times and is repeatable every time the script is looting and the player has another interactable object in their crosshairs. 

Not many people have found their way here since the mod isn't on either nexus or Bethesda but your last three contributors all report this issue.

If any other player is here and running the script without any crashes, let them speak now.

Whilst I appreciate and thank you for your time in creating the script. If others are having issues and you've moved on to something else, you should let us try and solve them for the benefit of everybody.

**Comment by fireundubh** [comment] 2016-12-01 16:45
As I've said repeatedly before, crashes and freezes are not caused by my scripts. I don't care how many people report them to me. It doesn't change the facts. Report stability issues to Bethesda.

**Comment by rahaney** [comment] 2016-12-01 20:01
Well if fallout is rock solid when your mod is loaded but switched off by the pipboy disk and then repeatedly crashes when turned back on and actively looting as above -> it's your mod/code.

When you hear hoofbeats, think of horses not zebras.

If anyone solves this, post a new issue and I'll gladly help test.

**Comment by rahaney** [comment] 2016-12-01 20:23
Btw you could simply say you are not involved with this anymore, will not be offering any support from now on and provided full credit is given to you as the creator of this mod then upload it to the nexus for others to take forward....

Once again, thank you for your time and effort as it is the only autoloot mod around for Fallout 4.
Best wishes,
R
